export const CHANGE_SEARCH_FIELD = "CHANGE_SEARCH_FIELD";

export const REQUEST_SPEECH_TO_TEXT_PENDING= "REQUEST_SPEECH_TO_TEXT_PENDING";
export const REQUEST_SPEECH_TO_TEXT_SUCCESS= "REQUEST_SPEECH_TO_TEXT_SUCCESS";
export const REQUEST_SPEECH_TO_TEXT_FAILED= "REQUEST_SPEECH_TO_TEXT_FAILED";

export const REQUEST_ROBOTS_PENDING = "REQUEST_ROBOTS_PENDING";
export const REQUEST_ROBOTS_SUCCESS = "REQUEST_ROBOTS_SUCCESS";
export const REQUEST_ROBOTS_FAILED= "REQUEST_ROBOTS_FAILED";

export const SPEECH_ON = "SPEECH_ON";
export const SPEECH_OFF= "SPEECH_OFF";
